{{- $outer := . -}}
{{- range $clusterIssuerName, $clusterIssuerValues := .Values.cloudflare }}
{{- with (merge (dict "clusterIssuerName" $clusterIssuerName "clusterIssuerValues" $clusterIssuerValues) $outer) }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .clusterIssuerName }}
  labels:
    app: {{ include "clusterIssuer.name" . }}
    app.kubernetes.io/name: {{ include "clusterIssuer.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: "clusterIssuer"
    helm.sh/chart: {{ include "clusterIssuer.chart" . }}
spec:
  acme:
    {{- toYaml .clusterIssuerValues.acme | nindent 4 }}
    solvers:
      - dns01:
          cloudflare:
            {{- with .clusterIssuerValues.apiTokenSecretRef }}
            apiTokenSecretRef:
              {{- toYaml . | nindent 14 }}
            {{- end -}}
        {{- with .clusterIssuerValues.dnsZones }}
        selector:
          dnsZones:
            {{- toYaml . | nindent 12 }}
        {{- end }}
{{- end }}
{{- end }}
